export interface Irecipes{
    "id":number,
    "title": string,
    "category": string,
    "cuisine": string,
    "mainIngredient": string,
    "description": string,
    "url": string,
    "urlHost": string,
    "prepTime": number,
    "cookTime": number,
    "totalTime": number,
    "ingredients": string,
    "directions": string,
    "tags": string,
    "rating": "",
    "publicUrl": string,
    "photoUrl": string,
    "private":string,
    "nutritionalScoreGeneric": "",
    "calories": number,
    "fat": string,
    "cholesterol": string,
    "sodium": string,
    "sugar": string,
    "carbohydrate": string,
    "fiber": string,
    "protein": string,
    "cost": ""
}