export interface IRecipe {
  id: number,
  title: string,
  course: string,
  cuisine: string,
  mainIngredient: string,
  description: string ,
  source: string,
  url: string,
  urlHost: string,
  prepTime: number,
  cookTime: number,
  totalTime: number,
  servings: number,
  yield: number | string,
  ingredients: string,
  directions: string,
  rating: string,
  publicUrl: string,
  photoUrl: string,
  private: string,
  nutritionalScoreGeneric: string,
  calories:number | string,
  fat: string ,
  cholesterol: string,
  sodium: string | number,
  sugar: string ,
  carbohydrate: string,
  fiber: string,
  protein: string,
  cost: string,
  tags: string,
}
