export  const recipes= [
    {
        "id": 1,
        "title": "California Roll Sushi Bowls",
        "category": "Dinner",
        "cuisine": "Asian",
        "mainIngredient": "Vegetables",
        "description": "The doner is a Turkish creation of meat, often lamb, but not necessarily so, that is seasoned, stacked in a cone",
        "url": "https://www.cookingclassy.com/california-roll-sushi-bowls/",
        "urlHost": "cookingclassy.com",
        "prepTime": 15,
        "cookTime": 25,
        "totalTime": 40,
        "ingredients": "2 cups dry California Calrose Sushi Rice\n5 Tbsp rice vinegar, (, divided)\n2 Tbsp granulated sugar\n1/2 tsp salt\n1/4 cup light mayonnaise\n1 1/2 Tbsp sriracha\n1/4 cup low-sodium soy sauce\n10 oz imitation crab, or lump crabmeat, (, torn or chopped into small bite size pieces)\n1 1/2 cups diced English cucumber\n3/4 cup roughly chopped matchstick carrots\n1 nori sheet (, chopped or crumbled into small pieces (add more if you'd like))\n1 1/2 Tbsp chopped pickled sushi ginger\n1 large avocado, (, peeled and diced)\nBlack and toasted sesame seeds, (, for garnish)",
        "directions": "Place rice in a fine mesh strainer and rinse under cold water until water runs clear (it will take about 2 minutes of rinsing). Tap bottom of strainer with palm of your hand until water no longer falls from strainer (it should be well drained). Transfer rice to a medium saucepan along with 2 1/4 cups water. Bring mixture to a full boil then reduce heat to low, cover with lid and simmer 15 minutes. Remove from heat, keep covered and let rest 15 minutes.\nMeanwhile, in a small saucepan combine 4 Tbsp of the vinegar with the sugar and salt. Heat over medium heat, cook and whisk until sugar has dissolved. Remove from heat, let cool while rice is resting then pour vinegar mixture over rice and toss to evenly coat.\nIn a small mixing bowl whisk together mayonnaise with sriracha. Thin with 1 1/2 tsp of water if desired. Transfer to a sandwich size resealable bag. Set aside.\nIn a small mixing bowl whisk together soy sauce and remaining 1 Tbsp vinegar, set aside. In a large mixing bowl gently toss together crab meat, cucumber, carrots, nori, ginger and avocado. Divide prepared rice among 4 or 5 bowls. Top with crab mixture then spoon soy sauce mixture over top of each serving. Cut a small tip from one corner of the resealable bag holding the sriracha mixture, drizzle over each serving. Serve immediately.\nRecipe source: adapted with changes from Whole Foods",
        "tags": "Easy, Salad",
        "rating": "",
        "publicUrl": "https://www.plantoeat.com/recipes/16687583",
        "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16687583/d99596b7acb8758e6d878ada11c36bd83c704cf4-original.jpg?1535321755",
        "private": "no",
        "nutritionalScoreGeneric": "",
        "calories": 465,
        "fat": "8 g",
        "cholesterol": "8 mg",
        "sodium": "1185 mg",
        "sugar": "9 g",
        "carbohydrate": "84 g",
        "fiber": "6 g",
        "protein": "10 g",
        "cost": ""
      },
     {
        "id": 2,
        "title": "Chicken Caesar Wraps",
        "category": "Lunch",
        "cuisine": "American",
        "mainIngredient": "Chicken",
        "description": "The doner is a Turkish creation of meat, often lamb, but not necessarily so, that is seasoned, stacked in a cone",
        "source": "https://www.favfamilyrecipes.com/chicken-caesar-wraps/",
        "url": "https://www.favfamilyrecipes.com/chicken-caesar-wraps/",
        "urlHost": "favfamilyrecipes.com",
        "prepTime": 0,
        "cookTime": 20,
        "totalTime": 20,
        "ingredients": "2-3 c. romaine lettuce\nCaesar dressing, (to taste.. the better the dressing, the better your wrap will be.. personally I like Brianna's bran\n1/3 c. Parmesan cheese, (freshly grated)\n1 chicken breast, (cooked & diced)\ncroutons, (coarsely chopped)\ndiced tomatoes, (lightly salted)\n2-3 tortilla wraps, (burrito sized, we like the herb flavored kind)",
        "directions": "Toss lettuce, dressing, cheese, chicken, and croutons in a large bowl until everything is lightly coated with dressing. Add tomatoes and lightly toss again. Place salad mixture in the middle of the wrap, wrap up tightly and serve!",
        "tags": "Chicken, Quick, Cheap",
        "publicUrl": "https://www.plantoeat.com/recipes/16687602",
        "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16687602/ba918c2550fd60a3f56da6cc510eb24b56752f63-original.jpg?1535321822",
        "private": "no",
        "nutritionalScoreGeneric": "",
        "calories": 280,
        "fat": "8g",
        "cholesterol": "25mg",
        "sodium": "580mg",
        "sugar": "2g",
        "carbohydrate": "36g",
        "fiber": "12%",
        "protein": "15g",
        "cost": ""
      },
      {
        "id": 3,
        "title": "Vegetarian Tacos with Avocado Cream",
        "category": "Breakfast",
        "cuisine": "American",
        "mainIngredient": "Vegetables",
        "description": "The doner is a Turkish creation of meat, often lamb, but not necessarily so, that is seasoned, stacked in a cone",
        "source": "https://emilykylenutrition.com/vegetarian-hummus-tacos/",
        "url": "https://emilykylenutrition.com/vegetarian-hummus-tacos/",
        "urlHost": "emilykylenutrition.com",
        "prepTime": 5,
        "cookTime": 5,
        "totalTime": 10,
        "ingredients": "For Avocado Cream\n1/2 avocado\n1 cup plain Greek Yogurt\n1 lime, (juiced)\n1 teaspoon homemade taco seasoning\nFor Tacos\n8 whole wheat tortillas\n1 cup roasted red pepper hummus\n1 cup grape tomatoes, (diced)\n1 small cucumber, (diced)\n1 bell pepper, (diced)\n1/2 cup black beans\n1/2 cup frozen corn, (thawed)\n1 cup greens, (shredded)\n1/2 cup fresh sprouts, or microgreens\n1/2 avocado, (diced)",
        "directions": "In a small food processor, blend together the avocado, Greek yogurt, lime juice, and taco seasoning until smooth. Set aside.\nSet out tortillas and fill with a hearty dollop of hummus.\nAdd your fresh toppings.\nTop with avocado cream.\nGarnish with sprouts.\nEnjoy!",
        "tags": "Vegan, Quick",
        "rating": "",
        "publicUrl": "https://www.plantoeat.com/recipes/16687702",
        "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16687702/089722a277be198555dd6c9c1f08476cc3b8eab3-original.jpg?1535322539",
        "private": "no",
        "nutritionalScoreGeneric": "",
        "calories": 410,
        "fat": "18g",
        "cholesterol": "5mg",
        "sodium": "680mg",
        "sugar": "6g",
        "carbohydrate": "54g",
        "fiber": "52%",
        "protein": "14g",
        "cost": ""
      },
      {
        "id": 4,
        "title": "Chicken and Lemon Risotto",
        "category": "Lunch",
        "cuisine": "Italian",
        "mainIngredient": "Rice & Grains",
        "description": "Chicken And Lemon Risotto With Reduced Sodium Chicken Stock, Butter, Boneless Skinless Chicken Breasts, Garlic, Lemon Juice, Fresh Oregano, Onion, Arborio Rice, Frozen Peas, Grated Lemon Peel, Grated Parmesan Cheese",
        "source": "https://www.yummly.com/recipe/Chicken-and-Lemon-Risotto-1407363",
        "url": "https://www.yummly.com/recipe/Chicken-and-Lemon-Risotto-1407363",
        "urlHost": "yummly.com",
        "prepTime": 0,
        "cookTime": 55,
        "totalTime": 55,
        "ingredients": "4 cups reduced sodium chicken stock\n3 tablespoons butter\n1 pound boneless skinless chicken breasts larger pieces halved\n2 cloves garlic crushed\n1/4 cup lemon juice\n2 tablespoons fresh oregano coarsely chopped\n1 onion medium, finely chopped\n1 1/2 cups arborio rice\n3/4 cup frozen peas\n2 teaspoons grated lemon peel finely\n1/4 cup grated parmesan cheese finely",
        "directions": "Place the stock and 1/2 cup water in a medium saucepan. Bring to a boil. Cover and reduce heat to low.\nMeanwhile, melt 1/2 the butter in large saucepan on medium heat. Add the chicken and cook until browned on both sides and just cooked through. Add the garlic, lemon juice and oregano and cook, stirring, until almost all the liquid has evaporated. Remove the chicken from pan and keep warm.\nMelt the remaining butter in the same pan. Add the onion and cook, stirring, until soft. Add the rice, stirring to coat it in the buttery juices. Reduce heat to medium-low. Add a ladleful of hot stock to rice mixture; stir constantly until liquid is absorbed. Continue to add stock, 1 ladleful at a time, stirring constantly until liquid is absorbed before adding more (this will take about 35 mins or until rice is tender but firm to the bite). After 30 mins, stir in the peas.\nAdd the lemon peel, cheese, and salt and pepper to taste. Serve the rice topped with chicken and additional Parmesan shavings, if desired.",
        "tags": "Chicken",
        "rating": "",
        "publicUrl": "https://www.plantoeat.com/recipes/16687774",
        "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16687774/ff717e9ea9e725eb270c6f4b58d38716164bb5cf-original.jpg?1535322745",
        "private": "no",
        "nutritionalScoreGeneric": "",
        "calories": 560,
        "fat": "15 g",
        "cholesterol": "100  mg",
        "sodium": "870  mg",
        "sugar": "3 g",
        "carbohydrate": "69 g",
        "fiber": "5 g",
        "protein": "36 g",
        "cost": ""
      },
      {
        "id": 5,
        "title": "Chicken, Broccoli Risotto",
        "category": "Lunch",
        "cuisine": "Italian",
        "mainIngredient": "Rice & Grains",
        "description": "Chicken, Broccoli Risotto With Arborio Rice, Dry White Wine, Chicken Stock, Leek, Butter, Parmesan Cheese, Chicken Breast, Broccoli, Medium Carrot, Olive Oil",
        "source": "https://www.yummly.com/recipe/Chicken_-Broccoli-Risotto-2035794",
        "url": "https://www.yummly.com/recipe/Chicken_-Broccoli-Risotto-2035794",
        "urlHost": "yummly.com",
        "prepTime": 0,
        "cookTime": 30,
        "totalTime": 30,
        "ingredients": "2/3 cup arborio rice 4.2oz, 125gr, or other rice specifically for risotto – Carnaroli or Vialone Nano\n1/2 cup dry white wine 4oz, 120ml\n2 1/4 cups chicken stock 18oz, 540ml\n1 leek medium, trimmed and sliced, divided\n1 tablespoon butter\n3/4 cup parmesan cheese 3oz, 90gr, – freshly grated\n1 chicken breast boneless, skinless, cut into small pieces\n1/2 head broccoli cut into florets with stem\n1 medium carrot cut into matchsticks\n1 tablespoon olive oil",
        "directions": "Heat chicken stock and keep hot over low heat.\nIn medium sauce pan heat butter; add half the leek and sauté until transparent.\nAdd rice and sauté, stirring, for 2 – 3 minutes until rice has white center.\nAdd white wine and stir.\nStart condimenti.\nWhen wine is almost absorbed add a 1/3 cup of stock, stir.  (No need to stir constantly but do stir from time to time.)\nWhen stock is almost absorbed add another 1/3 cup and continue adding 1/3 cup at a time and stirring.  Before adding the last 1/4 cup taste a few kernels of rice.  They should be just ‘al dente’ – slightly resistant to the tooth, but fully cooked.  If more stock is needed add it 1/8 cup at a time and waiting until almost completely absorbed.  At this point risotto will be thick but not stiff – there will still be visible liquid and it will not hold it’s shape on a plate.\nAdd the Parmesan, Condimenti, and stir gently.\nSpoon into a bowl or risotto platter and serve.\nCondimenti:\nHeat oil in a medium skillet, add remaining half leek and sauté until transparent.\nAdd chicken, broccoli, carrot and sauté 5  – 7 minutes.\nAdd 1/4 cup of hot stock, cover, reduce heat and cook until vegetables are tender and chicken done.\nRemove from heat and keep warm until needed.",
        "tags": "Chicken",
        "rating": "",
        "publicUrl": "https://www.plantoeat.com/recipes/16687800",
        "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16687800/9bac872caee028022ce69dce2f6ec1fe57b51b3f-original.jpg?1535322905",
        "private": "no",
        "nutritionalScoreGeneric": "",
        "calories": 400,
        "fat": "14 g",
        "cholesterol": "45  mg",
        "sodium": "590  mg",
        "sugar": "6 g",
        "carbohydrate": "43 g",
        "fiber": "4 g",
        "protein": "22 g",
        "cost": ""
      },
      {
        "id": 6,
        "title": "Banana Bread Mini Muffins Recipe by Tasty",
        "category": "Breakfast",
        "cuisine": "American",
        "mainIngredient": "Fruit",
        "description": "Here's what you need: ripe banana, egg, full-fat greek yogurt, honey, vanilla extract, whole wheat flour, baking soda, strawberry, dark chocolate chip, blueberry, walnuts",
        "source": "https://tasty.co/recipe/banana-bread-mini-muffins",
        "url": "https://tasty.co/recipe/banana-bread-mini-muffins",
        "urlHost": "tasty.co",
        "prepTime": 20,
        "cookTime": 20,
        "totalTime": 40,
        "ingredients": "3 ripe bananas\n2 eggs\n1/2 cup full-fat Greek yogurt\n1/3 cup honey\n1 teaspoon vanilla extract\n1 1/2 cups whole wheat flour\n1 teaspoon baking soda\nDiced strawberries\nDark chocolate chips\nBlueberries\nChopped walnuts",
        "directions": "Preheat oven to 350°F (180°C).\nIn a large bowl, mash the bananas into a fine paste using a fork.\nAdd the eggs and whisk together until well incorporated.\nAdd in the Greek yogurt, honey, and vanilla extract, then mix.\nPour the flour over the wet mixture then sprinkle in the baking soda.\nUsing a spatula, fold the wet and dry ingredients together until the dry bits of the flour have disappeared.\nUsing a medium ice cream scoop, portion the batter evenly into a greased muffin tin.\nTop the muffins with your choice of toppings.\nBake for 20 minutes, until the muffins have risen and set.\nUnmold from the tray and serve.\nEnjoy!",
        "tags": "Breakfast, Bakery Goods",
        "rating": "",
        "publicUrl": "https://www.plantoeat.com/recipes/16687848",
        "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16687848/e9ac6403eb5f10dc73302c0bd58480b307d2680c-original.jpg?1535323065",
        "private": "no",
        "nutritionalScoreGeneric": "",
        "calories": "",
        "fat": "",
        "cholesterol": "",
        "sodium": "",
        "sugar": "",
        "carbohydrate": "",
        "fiber": "",
        "protein": "",
        "cost": ""
      },
      {
        "id": 7,
        "title": "Protein-Packed Breakfast Bars Recipe by Tasty",
        "category": "Breakfast",
        "cuisine": "",
        "mainIngredient": "",
        "description": "Here's what you need: flax meal, water, rolled oats, quinoa, baking powder, salt, maple syrup, refined coconut oil, vanilla extract, ripe banana, peanut butter chocolate candy, peanut butter, mini chocolate chips, gala apple, walnuts, cinnamon, nutmeg, carrot, cinnamon, nutmeg, almond butter, almond butter, strawberry, raspberry, blueberry, nonstick cooking spray",
        "source": "https://tasty.co/recipe/protein-packed-breakfast-bars",
        "url": "https://tasty.co/recipe/protein-packed-breakfast-bars",
        "urlHost": "tasty.co",
        "prepTime": 20,
        "cookTime": 90,
        "totalTime": 110,
        "ingredients": "1/4 cup flax meal\n3/4 cup water\n6 cups rolled oats\n6 cups cooked quinoa\n4 teaspoons baking powder\n1 teaspoon salt\n1 cup maple syrup\n1/2 cup melted refined coconut oil\n2 teaspoon vanilla extract\n4 ripe mashed bananas\nPeanut Butter Chocolate Chip\n6 tablespoons peanut butter\n5 tablespoons mini chocolate chips\n3/4 cup diced gala apple\n6 tablespoons walnuts, chopped\n1 1/2 tablespoons cinnamon\n1/4 teaspoon nutmeg\n3/4 cup grated carrots\n3 teaspoons cinnamon\n1/4 teaspoon nutmeg\n3 tablespoons almond butter\n3 tablespoons almond butter\n1/3 cup diced strawberries\n1/3 cup raspberries\n1/3 cup blueberries\nNonstick cooking spray",
        "directions": "Preheat the oven to 375°F (190°C).\nTo make the flax eggs, combine the flax meal and water in a small bowl and mix well. Set aside for 10 minutes to thicken.\nIn a large bowl, combine the oats, quinoa, baking powder, salt, maple syrup, coconut oil, vanilla, flax eggs, and bananas, and mix until well-combined.\nDivide the base dough equally between 4 medium bowls.\nAdd the peanut butter and chocolate chips to a bowl and mix until combined.\nAdd the apple, walnuts, cinnamon, and nutmeg to another bowl and mix until combined.\nAdd the carrots, cinnamon, nutmeg, and almond butter to another bowl and mix until combined.\nAdd the almond butter, strawberries, raspberries, and blueberries to the last bowl and mix until combined.\nGrease 2, 9x13-inch (23x33-cm) baking pans with nonstick spray. Transfer the bar mixtures to the pans, packing each mixture into half of a pan with a spoon or spatula.\nBake for 25-30 minutes, until the edges are slightly golden brown.\nRemove the pans from the oven and let the bars cool for 20 minutes, then refrigerate for at least 30 minutes or up to 5 days. Gently cut each flavor into 6 bars, then remove from the pans with a spatula.\nEnjoy!",
        "tags": "Breakfast",
        "rating": "",
        "publicUrl": "https://www.plantoeat.com/recipes/16687888",
        "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16687888/b16ace53a4f663e77774571db54f16ac701ff494-original.jpg?1535323204",
        "private": "no",
        "nutritionalScoreGeneric": "",
        "calories": "",
        "fat": "",
        "cholesterol": "",
        "sodium": "",
        "sugar": "",
        "carbohydrate": "",
        "fiber": "",
        "protein": "",
        "cost": ""
      },
      {
        "id": 8,
        "title": "Healthy No Bake Peanut Butter Pretzel Granola Bars",
        "category": "Snacks and Sandwiches",
        "cuisine": "American",
        "mainIngredient": "",
        "description": "Healthy No-Bake Peanut Butter Pretzel Bars.",
        "source": "http://peanutbutterpluschocolate.com/healthy-no-bake-peanut-butter_pretzel-granola-bars/",
        "url": "http://peanutbutterpluschocolate.com/healthy-no-bake-peanut-butter_pretzel-granola-bars/",
        "urlHost": "peanutbutterpluschocolate.com",
        "prepTime": 5,
        "cookTime": 0,
        "totalTime": 5,
        "ingredients": "1 mashed banana, ripe\n3/4 c peanut butter\n1/4 c agave\n2 1/2 c rolled oats, (gluten-free)\n1/4 c pretzels pieces, (gluten-free)\n1 tbsp chia seeds",
        "directions": "In a large bowl, stir together the banana mash, peanut butter and agave until well combined. Add in the oats and chia seeds and stir well. Fold in the pretzel pieces.\nPress the mixture evenly into the bottom of an 8x8 inch pan lined with parchment paper.\nChill in the freezer for 20 minutes before cutting into 9 squares and serving.",
        "tags": "Dessert, Snack",
        "rating": "",
        "publicUrl": "https://www.plantoeat.com/recipes/16687930",
        "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16687930/cf62d2d92c4accd37c7238f93735181d1dcfbe98-original.jpg?1535323385",
        "private": "no",
        "nutritionalScoreGeneric": "",
        "calories": 240,
        "fat": "13g",
        "cholesterol": "",
        "sodium": "130mg",
        "sugar": "4g",
        "carbohydrate": "26g",
        "fiber": "5g",
        "protein": "9g",
        "cost": ""
      },
      {
        "id": 9,
        "title": "Slow Cooker Teriyaki Chicken + Crock-Pot Giveaway",
        "category": "Dinner",
        "cuisine": "Asian",
        "mainIngredient": "Chicken",
        "description": "This Slow Cooker Teriyaki Chicken recipe is simple to make, full of great flavor, and made with natural sweeteners.",
        "source": "https://www.gimmesomeoven.com/slow-cooker-teriyaki-chicken-teriyaki/",
        "url": "https://www.gimmesomeoven.com/slow-cooker-teriyaki-chicken-teriyaki/",
        "urlHost": "gimmesomeoven.com",
        "prepTime": 10,
        "cookTime": 250,
        "totalTime": 260,
        "ingredients": "2 lbs boneless, skinless chicken breasts\n2 cloves garlic, minced\n1/2 cup chopped white onion\n1/2 cup honey\n1/2 cup soy sauce, (use low-sodium if desired)\n1/4 cup rice wine vinegar\n1 Tbsp. chopped fresh ginger\n1/8 tsp. freshly ground black pepper\n1/4 cup cold water\n3 Tbsp. cornstarch\noptional toppings: sliced scallions and toasted sesame seeds",
        "directions": "Add the chicken breasts to the bottom of your slow cooker in a single layer.\nIn a separate bowl, whisk together the garlic, onion, honey, soy sauce, rice wine vinegar, ginger, and black pepper until combined. Pour the mixture on top of the chicken breasts. Cover slow cooker, and cook on high for 4-5 hours, or until the chicken is cooked through and shreds easily with a fork. Remove the chicken with a slotted spoon to a separate bowl and shred it using two forks. Transfer the remaining teriyaki sauce from the slow cooker to a medium saucepan.\nMeanwhile in a separate bowl, whisk together the cold water and cornstarch until the cornstarch is dissolved and no longer lumpy. Pour the cornstarch slurry into the teriyaki sauce mixture, and whisk to combine. Bring the mixture to a boil over medium-high heat, and let it boil for about 1-2 minutes or until thickened. Remove from heat, and pour the sauce on top of the shredded chicken. Toss to combine.\nServe topped with scallions (green onions) and toasted sesame seeds if desired.",
        "tags": "Crock Pot, Chicken, Slow Cooker",
        "rating": "",
        "publicUrl": "https://www.plantoeat.com/recipes/16689229",
        "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16689229/996f102a3864582b550a11327cc39380b8da75c6-original.jpg?1535328708",
        "private": "no",
        "nutritionalScoreGeneric": "",
        "calories": "",
        "fat": "",
        "cholesterol": "",
        "sodium": "",
        "sugar": "",
        "carbohydrate": "",
        "fiber": "",
        "protein": "",
        "cost": ""
      },
      {
        "id": 10,
        "title": "Fiesta Chicken Crockpot Recipe",
        "course": "Dinner",
        "cuisine": "Mexican",
        "mainIngredient": "Poultry",
        "description": "The doner is a Turkish creation of meat, often lamb, but not necessarily so, that is seasoned, stacked in a cone",
        "source": "http://mylitter.com/fiesta-chicken-crockpot-recipe/",
        "url": "http://mylitter.com/fiesta-chicken-crockpot-recipe/",
        "urlHost": "mylitter.com",
        "prepTime": 0,
        "cookTime": 360,
        "totalTime": 360,
        "ingredients": "4 chicken breast, (frozen or raw)\n1 packet Taco Seasoning, (by the salad dressing)\n1 can black beans, (drained and rinsed)\n1 can salsa not drained\n1 can corn not drained",
        "directions": "Looking for a new slow cooker recipe to feed the troops? This Fiesta Chicken Crockpot Recipe is a great one to add to the rotation!\nYou might have seen this recipe around the internet this past week… my Fiesta Chicken crockpot recipe. Those of you who have been reading my site for a while might have recognized my kitchen anyway…\nI make this for dinner often. It is a simple, easy and DELICIOUS chicken crock pot recipe that my kids love. I love it as well for that matter…\nAnyway, I was in a hurry and made it for dinner last week and was out of a few ingredients and made some substitutions. It looked really pretty when I had it all together and so I snapped a picture and figured I would let you guys know what I was having for dinner.\nWell, 26 MILLION people saw my picture last week with over 550,000 shares of my picture & recipe!! (Then of course you have countless people who stole my picture and reposted exactly my word for word comments and directions as their own, and those were shared a crazy number of times…) But in the end, it is a DANG good chicken recipe!\nI was out of the standard Ranch packet you are supposed to dump on the top, but I had this packet of Fiesta Ranch and so I used that… OMGosh! It made it soooooo good!!\nThis recipe is sooooo easy! You can use raw, frozen or unfrozen chicken. You dump it all in the crockpot, sprinkle the dip packet over it all, and then cook it on high for 4 hours or 6 on low. Then shred the chicken with forks and mix it all up. It looks a little sketchy at this point, but don’t worry. Then we make rice, and serve this over the rice using tortillas to scoop it up OR you can just make chicken tacos. So many choices!\nIf it is a little soupy that is ok. Leave the lid off for a little bit and the liquid will disappear. I think it is good with a little sauce though personally.\nInstead of the usual Rotel I used petite diced tomatoes drained, as my little kids don’t like the spice from Rotel.\nThe cream cheese doesn’t need to cook all day with the chicken. In fact, it might curdle if you boil it. I typically toss it in about 40 minutes before we eat, it just needs to get soft enough for you to stir in.\n**If you don’t feel like heading into the store for all your shopping list for this, you might try the Walmart Grocery Pickup if it’s available in your area (there’s coupon codes all the time)\nCook on high in the slow cooker for 4 hours or 6 on low. Shred with forks and eat over rice with tortillas.\nIf using the Instant Pot, use raw chicken. Cover the chicken with the ingredients listed. Press the poultry button then add 5 minutes to cook the chicken for a total of 20 minutes (some prefer 25 minutes).\nThe Instant Pot will release the pressure. Your chicken will be ready to shred and serve!\nThis Hamilton Beach Stay or Go is currently my favorite Crock Pot. I needed to get one with the latch over the top after one too many spills while taking dinner to a party, friends, or church. Plus they are often 50% off or more with free shipping.\nIf you are having a hard time finding the Fiesta Ranch in your grocery store, they are in all of mine by the salad dressing usually on the top shelf, you can order some Fiesta Ranch HERE.\nIf you like Crock Pot recipes as much as I do, I put together a few of my FAVORITE easy Crock Pot recipes in one place. Head on over HERE to check them out!",
        "tags": "Chicken, Slow Cooker",
        "rating": "",
        "publicUrl": "https://www.plantoeat.com/recipes/16689260",
        "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16689260/2b7f200e5109759150fec43af0e225647611ce23-original.jpg?1535328913",
        "private": "no",
        "nutritionalScoreGeneric": "",
        "calories": "",
        "fat": "",
        "cholesterol": "",
        "sodium": "",
        "sugar": "",
        "carbohydrate": "",
        "fiber": "",
        "protein": "",
        "cost": ""
      },
      {
        "id": 11,
        "title": "Orange Chipotle Chicken with Cilantro Rice",
        "course": "Main Course",
        "cuisine": "American",
        "mainIngredient": "Poultry",
        "description": "",
        "source": "https://www.cleaneatingmag.com/recipes/orange-chipotle-chicken-with-cilantro-rice",
        "url": "https://www.cleaneatingmag.com/recipes/orange-chipotle-chicken-with-cilantro-rice",
        "urlHost": "cleaneatingmag.com",
        "prepTime": 10,
        "cookTime": 6,
        "totalTime": 16,
        "servings": 4,
        "yield": 4,
        "ingredients": "1 tsp chile powder\n1/2 tsp ground cumin\n1/2 tsp sea salt, divided\n1 tsp safflower oil\n4 boneless, skinless chicken breasts, (about 1 lb) rinsed and patted dry, pounded 1/2-inch thick\nJuice 1 medium navel orange, (1/3 cup orange juice)\n2 tbsp pure maple syrup\n1 tbsp chopped chipotle chiles in adobo sauce\n1 tsp orange zest\n2 cups cooked brown rice\n1/4 packed cup chopped cilantro leaves",
        "directions": "In a small bowl, combine chile powder, cumin and 1/4 tsp salt. Heat oil in a large nonstick skillet to medium-high. Tilt skillet to coat bottom lightly. Season both sides of chicken with chile-cumin mixture and cook for 3 minutes per side or until no longer pink in center. Remove from skillet and set aside.\nAdd orange juice and maple syrup to juice and bits left in skillet and cook for 1 minute to thicken slightly (until it measures 1/4 cup liquid), stirring constantly. Remove from heat, stir in chipotle chiles in adobo sauce and orange zest. Add chicken back to skillet, return to heat and cook for 1 minute on medium-high, turning constantly.\nIn a medium bowl, combine rice, cilantro and remaining 1/4 tsp salt. Serve chicken over rice and spoon any excess glaze over top chicken pieces.",
        "tags": "Chicken, Budget Friendly",
        "rating": "",
        "publicUrl": "https://www.plantoeat.com/recipes/16727990",
        "photoUrl": "https://plantoeat.s3.amazonaws.com/recipes/16727990/a03bff7a41182945fde5f0eff18c57db9765dd4b-original.jpg?1535642619",
        "private": "no",
        "nutritionalScoreGeneric": "",
        "calories": 283,
        "fat": "4 g",
        "cholesterol": "32 mg",
        "sodium": "337 mg",
        "sugar": "8 g",
        "carbohydrate": "32 g",
        "fiber": "2 g",
        "protein": "29 g",
        "cost": ""
      }
    ]